checks:
    python:
        code_rating: true
        duplicate_code: true
        classes_valid_slots: true
    javascript: true
filter:
    excluded_paths:
        - '*/migrations/*'
build:
    environment:
        python: 3.6
    dependencies:
        override:
          - pip install https://github.com/WeblateOrg/weblate/archive/master.zip
          - pip install https://github.com/nijel/thepay/archive/weblate.zip
          - pip install https://github.com/nijel/fakturace/archive/master.zip
          - pip install https://github.com/WeblateOrg/hosted/archive/master.zip
          - pip install -r requirements.txt
          - pip install -r requirements-test.txt
    nodes:
        analysis:
            tests:
                override:
                  -
                    command: pylint-run --rcfile=.pylintrc
                    idle_timeout: 360
                  - py-scrutinizer-run
        tests:
            tests:
                override:
                    -
                        command: ./manage.py compilemessages
                    -
                        command: ./manage.py collectstatic --noinput
                    -
                        command: coverage run --source . ./manage.py test
                    -
                        command: coverage combine
                        coverage:
                            file: .coverage
                            format: py-cc
