checks:
    python:
        code_rating: true
        duplicate_code: true
        classes_valid_slots: true
    javascript: true
filter:
    excluded_paths:
        - '*/migrations/*'
build:
    environment:
        python: 3.6
    dependencies:
        override:
          - pip install https://github.com/WeblateOrg/weblate/archive/master.zip
          - pip install https://github.com/nijel/thepay/archive/weblate.zip
          - pip install https://github.com/nijel/fakturace/archive/master.zip
          - pip install https://github.com/WeblateOrg/hosted/archive/master.zip
          - pip install -r requirements.txt
          - pip install -r requirements-test.txt
          - pip install mysqlclient
    nodes:
        analysis:
            tests:
                override:
                  -
                    command: pylint-run --rcfile=.pylintrc
                    idle_timeout: 360
                  - py-scrutinizer-run
        tests:
            services:
                mariadb: 10
            tests:
                before:
                    -
                        command: mysql -e 'CREATE DATABASE weblate_web CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;' -uroot
                    -
                        command: mysql -e 'CREATE DATABASE payments CHARACTER SET utf8mb4 COLLATE utf8mb4_general_ci;' -uroot
                    -
                        command: mysqldump -u root --databases weblate_web payments
                override:
                    -
                        command: ./scripts/generate-locales || true
                    -
                        command: coverage run --source . ./manage.py migrate
                    -
                        command: coverage run --source . ./manage.py migrate --database payments_db
                    -
                        command: coverage run --source . ./manage.py test
                    -
                        command: coverage combine
                        coverage:
                            file: .coverage
                            format: py-cc
