dist: xenial
language: python
python:
  - "3.5"
  - "3.7"
env:
  global:
    - DJANGO_SETTINGS_MODULE=wlhosted.settings_test
install: 
  # Get newer pip and whell for binary caching support
  - pip install --upgrade pip wheel Cython
  - pip install https://github.com/nijel/thepay/archive/weblate.zip
  - pip install -r requirements-test.txt
script: 
  - coverage run `which weblate` test
  - ./setup.py sdist
  - twine check dist/*
  - flake8
after_script:
  - coverage xml
  - codecov
  - python-codacy-coverage
cache: pip
git:
  depth: 10
addons:
  apt:
    packages:
      - texlive-latex-recommended
      - libcairo-dev
      - gir1.2-pango-1.0
      - libgirepository1.0-dev
      - libacl1-dev
