language: python
python:
  - "3.5"
sudo: false
env:
  global:
    - DJANGO_SETTINGS_MODULE=wlhosted.settings_test
install: 
  # Get newer pip and whell for binary caching support
  - pip install --upgrade pip wheel
  - pip install https://github.com/nijel/thepay/archive/weblate.zip
  - pip install -r requirements-test.txt
script: 
  - coverage run `which weblate` test
  - ./setup.py sdist
  - twine check dist/*
after_script:
  - coverage xml
  - codecov
  - python-codacy-coverage
cache: pip
git:
  depth: 10
  submodules: false
